feat: add OperationalError cause property
Financial-Times/dotcom-reliability-kit pull request #98
Opened 2022-08-03 12:08 UTC by andygout

FTDCS-250

Jira card: https://financialtimes.atlassian.net/jira/software/c/projects/FTDCS/boards/1426?modal=detail&selectedIssue=FTDCS-250

> **Rowan Manning:** @andygout [pointed out](https://financialtimes.slack.com/archives/CPNKK12S1/p1659013086713049?thread_ts=1659003590.492259&cid=CPNKK12S1) in one of my examples for handling errors we lose some information about the original error. I’ve had a potential solution in mind for this for a while and it’s worth getting down on paper.

> I think that OperationalError should have a new first-class property named cause. This expects another Error object and marks that error as the root cause of the operational error. This will allow us to use generic messages in some places but still capture the original error information. Using the example from the error handling docs, we could update it to be:

```js
try {
    fruit.stockLevel = await fruitApiClient.getStockLevel(fruit.id);
} catch (error) {
    console.warn({
        event: 'RECOVERABLE_ERROR',
        error: serializeError(new OperationalError({
            code: 'FRUIT_STOCK_LEVEL_FAILED',
            message: `The Fruit API did not return a stock level for ID ${fruit.id}`,
            relatesToSystems: ['fruit-api'],
            cause: error // This is the new code
        }))
    });
    fruit.stockLevel = null;
}
```

> We’d also want to update our logger so that it exposes this information and also serialises any errors on the cause property, e.g. the log output could change to:

```js
{
    event: 'RECOVERABLE_ERROR',
    message: 'OperationalError: The Fruit API did not return a stock level for ID X',

    error: {
        // missing some properties for brevity
        name: 'OperationalError',
        code: 'FRUIT_STOCK_LEVEL_FAILED',
        message: 'The Fruit API did not return a stock level for ID X',
        
        cause: {
            name: 'Error',
            code: null,
            message: 'HTTP 503'
        }
    },

    app: {
        // etc
    }
}
```

2022-08-03 12:17 UTC, andygout commented on packages/serialize-error/test/lib/index.spec.js
> +				});
I could have gone to town on testing the serialisation of the `cause` error to provide the same coverage that is given for the subject (i.e. containing) error, e.g. when the `cause` value is the result of `serialiseError()` being called with:
- an error object
- en error-like object
- a string
- a number
- an array

However, the `serialiseError()` is already being tested so thoroughly by the subject error, so ensuring that the root cause error `message` value is as expected felt to be a sufficient measure for testing this.

2022-08-03 12:21 UTC, andygout commented
> We’d also want to update our logger so that it exposes this information

From what I can tell, the `cause` value of error should be surfaced via the inclusion of the `error` property (in which it is situated) and that no changes are required to `packages/log-error/lib/index.js` but please let me know if I have misunderstood something.

2022-08-03 12:28 UTC, rowanmanning requested changes
This is looking great, really excellent 🙂 and I think it'll make `OperationalError` a lot more useful when it starts appearing in apps.

My one change request is that we need to update the READMEs for a few of the packages:

* In the serialize-error README [here](https://github.com/Financial-Times/dotcom-reliability-kit/tree/main/packages/serialize-error#serializederror-type) and [here](https://github.com/Financial-Times/dotcom-reliability-kit/tree/main/packages/serialize-error#serializeerror) (also don't forget to update the table of contents which is manual for now)
* In the errors README [here](https://github.com/Financial-Times/dotcom-reliability-kit/tree/main/packages/errors#operationalerrorrelatestosystems) (also the ToC)

2022-08-03 12:28 UTC, rowanmanning commented on docs/getting-started/handling-errors.md
> +                    cause: error
**praise:** nice 👏 this is a much better example

2022-08-03 12:28 UTC, rowanmanning commented on docs/getting-started/throwing-errors.md
> +You might create an `OperationalError` instance in reaction to an error that has been caught. The root cause error and all the diagnostic information it contains can be included in the `OperationalEr
**praise:** great explanation and example

2022-08-03 12:28 UTC, rowanmanning commented on packages/serialize-error/lib/index.js
> +		errorProperties.cause = serializeError(error.cause);
**thought:** maybe down the line we need to think about whether to limit the recursion here? I don't think in this PR but I guess it's a possible vector for errors to creep in. Though tbh I think you'd have to try quite hard to make this infinitely recurse 🤷 anyway not something to address now

2022-08-04 10:32 UTC, rowanmanning approved these changes
Looks really great 👍 thanks Andy! Feel free to merge

2022-08-04 10:44 UTC, merged